//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public int idDetalleCompra { get; set; }
        public Nullable<int> idCompra { get; set; }
        public Nullable<int> idProducto { get; set; }
        public decimal precioCompra { get; set; }
        public int cantidad { get; set; }
        public decimal montoTotal { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
