//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUIA_RUTA
    {
        public int idGuia { get; set; }
        public Nullable<int> idVenta { get; set; }
        public string direccionEntrega { get; set; }
        public Nullable<System.DateTime> fechaEnvio { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string estado { get; set; }
    
        public virtual VENTAS VENTAS { get; set; }
    }
}
