//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        public int idPedido { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int prioridad { get; set; }
        public string tipoComprobante { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
