//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCompras
    {
        public int idCompra { get; set; }
        public string nombreUsuario { get; set; }
        public string razonSocial { get; set; }
        public string tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public Nullable<decimal> montoTotal { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    }
}
